repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.0.0
    hooks:
      - id: codespell
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-unit-tests
      - id: go-mod-tidy
      # - id: go-fmt
      # - id: go-vet
      # - id: go-lint
      # - id: go-imports
      # - id: go-cyclo
      #   args: [-over=15]
      # - id: validate-toml
      # - id: no-go-testing
      # - id: golangci-lint
      # - id: go-critic
